-- MySQL Script generated by MySQL Workbench
-- Thu May 16 08:38:58 2024
-- Model: I Lost It    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ilostit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ilostit` ;

-- -----------------------------------------------------
-- Schema ilostit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilostit` DEFAULT CHARACTER SET utf8 ;
USE `ilostit` ;

-- -----------------------------------------------------
-- Table `ilostit`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ilostit`.`members` ;

CREATE TABLE IF NOT EXISTS `ilostit`.`members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(50) NULL,
  `firstName` VARCHAR(30) NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `isVerified` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `isMod` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueMember` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilostit`.`objects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ilostit`.`objects` ;

CREATE TABLE IF NOT EXISTS `ilostit`.`objects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `classroom` VARCHAR(10) NOT NULL,
  `brand` VARCHAR(30) NULL,
  `color` VARCHAR(15) NULL,
  `value` DECIMAL(6,2) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `memberOwner_id` INT NOT NULL,
  `memberFinder_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Objects_MembersOwner_idx` (`memberOwner_id` ASC),
  INDEX `fk_Objects_MembersFinder_idx` (`memberFinder_id` ASC),
  UNIQUE INDEX `UniqueObject` (`title` ASC, `type` ASC, `memberOwner_id` ASC),
  CONSTRAINT `fk_Objects_Members`
    FOREIGN KEY (`memberOwner_id`)
    REFERENCES `ilostit`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Objects_Members1`
    FOREIGN KEY (`memberFinder_id`)
    REFERENCES `ilostit`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ilostit`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ilostit`.`images` ;

CREATE TABLE IF NOT EXISTS `ilostit`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `object_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueImage` (`name` ASC),
  INDEX `fk_Images_Objects_idx` (`object_id` ASC),
  CONSTRAINT `fk_Images_Objects`
    FOREIGN KEY (`object_id`)
    REFERENCES `ilostit`.`objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
